### ISSUE TITLE
ActionView::Template::Error (undefined method `name' for nil:NilClass)

### ISSUE THREAD

**Issue by iomode** [braini75/msproject_import#4]
I am using msproject_import with easyredmine (2015-07-26) v3.1.0 (based on redmine v3.1.0).
Installation worked fine but when I upload a msproject xml file I get a 500 Internal Server Error.
All users are correctly assigned and uploading works fine but something goes wrong afterwords.
I already tried updating/cache cleaning/permissions checking but it still fails.
Is this plugin compatible with redmine 3.1.0?

```
.....
-----------INFO:  Status: 1
.....
-----------INFO:  Status: 1
.....
-----------INFO:  Status: 1
.....
-----------INFO:  Status: 1
Rendered plugins/msproject_import/app/views/msproj_imp/analyze.html.erb within layouts/base (8.2ms)
Completed 500 Internal Server Error in 4685ms (ActiveRecord: 7.5ms)

ActionView::Template::Error (undefined method `name' for nil:NilClass):
    32:                 
    33:         %>
    34:         <tr>
    35:                 <td><%= task[0].name %></td>
    36:                 <td><%= assigned_to[1] %></td>
    37:                 <td><%= assigned_to[2].name unless assigned_to[3]>2 %></td>
    38:                 <td><%= I18n.t('user_imp_status_' + assigned_to[3].to_s)%></td>
  lib/redmine/sudo_mode.rb:63:in `sudo_mode'
```

**Comment by braini75** [comment]
I’ve just tested the plugin against redmine 3.1. It is working without any problem.
The attached error says that the mapping does not find the “name” of the mapped user. Make sure that assign users will have firstname and lastname attribute set.

**Comment by mrhatch** [comment]
I can't seem to get this plugin to work on Redmine 3.1.1  I receive the following message:

Processing by MsprojImpController#upload as HTML
  Parameters: {"project_id"=>"fy-15-icarc-support"}
  Current user: mike (id=5)
  Rendered plugins/msproject_import/app/views/msproj_imp/upload.html.erb within layouts/base (2.0ms)
Completed 200 OK in 43ms (Views: 30.1ms | ActiveRecord: 5.6ms)
Started POST "/msproject_import/analyze?project_id=fy-15-icarc-support" for 192.168.0.115 at 2015-10-08 17:21:44 +0000
Processing by MsprojImpController#analyze as HTML
  Parameters: {"utf8"=>"✓", "authenticity_token"=>"qPJ4QPN3NU/u1ltuW22rAkSXsVfseeIlTmfx+ARY3LdiFkRWN5WWufgvQEZVrbjUIEDHdnnP63Ftb1QCMkYQ0w==", "uploaded_file"=>#<ActionDispatch::Http::UploadedFile:0x007f9ab6e33688 @tempfile=#<Tempfile:/tmp/RackMultipart20151008-8026-1p2j44s.xml>, @original_filename="icarcims.xml", @content_type="text/xml", @headers="Content-Disposition: form-data; name=\"uploaded_file\"; filename=\"icarcims.xml\"\r\nContent-Type: text/xml\r\n">, "commit"=>"Analyze", "project_id"=>"fy-15-icarc-support"}
  Current user: mike (id=5)
upload xml file: ActionDispatch::Http::UploadedFile: #<ActionDispatch::Http::UploadedFile:0x007f9ab6e33688 @tempfile=#<Tempfile:/tmp/RackMultipart20151008-8026-1p2j44s.xml>, @original_filename="icarcims.xml", @content_type="text/xml", @headers="Content-Disposition: form-data; name=\"uploaded_file\"; filename=\"icarcims.xml\"\r\nContent-Type: text/xml\r\n"> : icarcims.xml : uploaded_path: /tmp/RackMultipart20151008-8026-1p2j44s.xml
Completed 500 Internal Server Error in 2992ms (ActiveRecord: 2.7ms)

TypeError (no implicit conversion of nil into String):
  lib/redmine/sudo_mode.rb:63:in `sudo_mode'

**Comment by braini75** [comment]
Easyredmine is able to Import MS Project XML files with ist own function:
<More>  => <Administration> => <Data templates>

**Comment by mrhatch** [comment]
Thomas,

Thanks for your response, I had been using ProjectLibre to generate my xml
files, and after finding another tool to generate the xml file I was able
to get it to import.  The problem appears to be with the XML.  Thanks for
looking into this.

Mike

Michael Hatch
mrhatch@innocent.com
443-305-9363
